# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe885250516eef1205cf6b376417a46dafa1ea86c55c4f1eabbd2549d64e1de7b9562ec5ecfeca4b5305acb0f21505038c4c159c5a81b7ebf444b5cdae35a5d

test:
  secret_key_base: 4b8b60074a8e6326c9181cea30674ec8c3636bdae916685f662ca0b1166864d57845582c8d1b99078e76fac0d385a83ea6e0de60c769c365febf4798473d3f6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
